config/routes.rb
CourseTracker::Application.routes.draw do

  devise_for :users

  get 'dashboard' => 'home#dashboard', :as => :dashboard

  shallow do
    resources :projects do
      resources :tasks do
        resources :action_items, :path => :actions, :as => :actions
        resources :action_items
      end
    end
  end
  #resources :tasks
  #resources :action_items, :path => :actions, :as => :actions

  root 'home#index'

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  #
  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  belongs_to :task
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :user_id, :presence => true
  validates :name, :presence => true
  belongs_to :user
  has_many :tasks
  has_many :actions, :through => :tasks, :source => :action_items
  scope :for, lambda { |id| where(:user_id => id) }

  def progress
    return 0 if tasks.empty?
    ((completed_task_count.to_f / tasks.count.to_f) * 100).to_i
  end

  private
  def completed_task_count
    tasks.where(:completed => true).count
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :actions, :class_name => ActionItem
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, :dependent => :destroy
  has_many :tasks,    :through => :projects
  has_many :actions,  :through => :tasks, :source => :action_items
end

app/controllers/action_items_controller.rb
class ActionItemsController < ResourceController

  def create
    create! { dashboard_url }
  end

  private
  def permitted_params
    params.permit(:action_item => %i{task_id name description tags completed in_progress})
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :dashboard

  def index
  end

  def dashboard
    @projects = Project.for(current_user.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ResourceController

  private
  def permitted_params
    params.permit(:project => %i{user_id name description tags completed in_progress})
  end
end

app/controllers/resource_controller.rb
class ResourceController < InheritedResources::Base
  before_filter :authenticate_user!

  def create
    create! { dashboard_path }
  end

end

app/controllers/tasks_controller.rb
class TasksController < ResourceController

  def create
    create! { dashboard_url }
  end

  private
  def permitted_params
    params.permit(:task => %i{project_id name description tags completed in_progress})
  end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/action_items/_form.html.erb
<%= simple_form_for([task, @action_item ||= ActionItem.new]) do |f| %>
  <fieldset>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :task_id, :as => :hidden, :input_html => { :value => task.id } %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :completed %>
    <%= f.input :in_progress %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  </fieldset>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing action_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<h1>Listing action_items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Completed</th>
      <th>In progress</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @action_items.each do |action_item| %>
      <tr>
        <td><%= action_item.name %></td>
        <td><%= action_item.description %></td>
        <td><%= action_item.completed %></td>
        <td><%= action_item.in_progress %></td>
        <td><%= link_to 'Show', action_item %></td>
        <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
        <td><%= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New action_item</h1>

<%= render 'form' %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @action_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @action_item.completed %>
</p>

<p>
  <strong>In progress:</strong>
  <%= @action_item.in_progress %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>

app/views/home/dashboard.html.erb
<div id='dashboard-wrapper'>
  <div class='row'>
    <div id='project-list' class="large-8 columns">
      <% @projects.each do |project| %>
        <h3 class='project'><%= project.name %><small><%= link_to "Add Task", "#", :'data-reveal-id' => "add-task-#{project.id}", :class => "button tiny radius right" %></small><span class='progress right'><span class='meter' style='width:<%= "#{project.progress}%" %>;'><%= "#{project.progress}%" %></span></span></h3>
        <div>
          <div id="tasks-<%=project.id%>">
            <div id='add-task-<%=project.id%>' class='reveal-modal'>
              <%= render :partial => 'tasks/form', :locals => { :project => project }  %>
            </div>
            <% project.tasks.each do |task| %>
              <h4 class='task'><%= task.name %><small><%= link_to "Add Action", "#", :'data-reveal-id' => "add-action-#{task.id}", :class => "button tiny radius right" %></small></h4>
              <div>
                <div id="actions-<%=task.id%>">
                  <div id='add-action-<%=task.id%>' class='reveal-modal'>
                    <%= render :partial => 'action_items/form', :locals => { :task => task }  %>
                  </div>
                  <% task.actions.each do |action| %>
                    <h5 class='action'><%= action.name %></h5>
                    <div></div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="large-4 columns">
      <div class='panel'>
        <%= link_to "Add Project", "#", :'data-reveal-id' => 'add-project-modal', :class => "button large radius" %>
      </div>
    </div>
  </div>
  <div id='add-project-modal' class='reveal-modal'>
    <%= render :partial => 'projects/form' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="large-stripe mint">
  <header class="home">
    <div class="row">
      <div class="large-6 columns centered">
        <h1>pp<small>&</small>pt</h1>
        <h4 class="subheader">Project Planner <big>&</big> Progress Tracker (PP&PT)</h4>
      </div>
      <div class="large-6 columns">
      </div>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id='content-wrapper'>
      <div class=" sticky">
        <nav class="top-bar" style="margin:0;">
          <ul class="title-area">
            <!-- Title Area -->
            <li class="name">
              <h1><a href="#">pp&pt</a></h1>
            </li>
            <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
          </ul>

          <section class="top-bar-section">
            <ul class="right">
              <li class="divider"></li>
              <li class="active"><a href="#">Main Item 1</a></li>
              <li class="divider"></li>
              <li><a href="#">Main Item 2</a></li>
              <li class="divider"></li>
            </ul>
          </section>
        </nav>
      </div>

      <div class="row">
        <div class="large-12 columns alerts">
          <% if notice %>
            <div data-alert class="alert-box radius center">
              <%= notice %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
          <% if alert %>
            <div data-alert class="alert-box alert radius center">
              <%= alert %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project ||= Project.new) do |f| %>
  <fieldset>
  <%= f.error_notification %>

    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <%= f.input :name %>
    <%= f.input :description, :as => :text %>
    <%= f.input :tags %>
    <%= f.input :completed %>
    <%= f.input :in_progress %>

    <div class="actions">
      <%= f.button :submit %>
    </div>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Completed</th>
      <th>In progress</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.tags %></td>
        <td><%= project.completed %></td>
        <td><%= project.in_progress %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @project.tags %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @project.completed %>
</p>

<p>
  <strong>In progress:</strong>
  <%= @project.in_progress %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for([project, @task ||= Task.new]) do |f| %>
  <fieldset>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :project_id, :as => :hidden, :input_html => { :value => project.id } %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :completed %>
      <%= f.input :in_progress %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </fieldset>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Completed</th>
      <th>In progress</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.completed %></td>
        <td><%= task.in_progress %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>In progress:</strong>
  <%= @task.in_progress %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>